server:
  port: 8081
spring:
  application:
    name: supportportal
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5438/supportportal
    username: cami
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true